In [63]:
import mlxtend as ml #Machine Learning extensions

In [64]:
import pandas as pd

In [95]:
import numpy as np

##Import DBs

In [65]:
UCI=pd.read_csv('https://github.com/dbdmg/data-science-lab/raw/master/datasets/online_retail.csv') #Online Retail Dataset

In [66]:
UCI.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [67]:
COCO=pd.read_json('https://raw.githubusercontent.com/dbdmg/data-science-lab/master/datasets/modified_coco.json')

In [68]:
COCO.head()

,file_name,image_id,annotations
0,000000095096.png,95096,"[car, car, train, stop sign]"
1,000000307153.png,307153,"[person, person, person, person, person, bench..."
2,000000252022.png,252022,[stop sign]
3,000000171269.png,171269,"[person, fire hydrant]"
4,000000229507.png,229507,"[bicycle, bicycle, fire hydrant]"

In [69]:
COCO['annotations']

0                            [car, car, train, stop sign]
1       [person, person, person, person, person, bench...
2                                             [stop sign]
3                                  [person, fire hydrant]
4                        [bicycle, bicycle, fire hydrant]
                              ...
4995                                          [stop sign]
4996                                          [stop sign]
4997                                       [fire hydrant]
4998    [person, person, person, person, person, perso...
4999    [person, person, person, person, bench, fork, ...
Name: annotations, Length: 5000, dtype: object

###First Point

In [70]:
UCI.isna().sum() #Number of Nan values in the Dataset

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [71]:
index_to_drop = [] 

for i, invoice in enumerate(UCI['InvoiceNo']): #index, value
    if invoice[0] == 'C':
        index_to_drop.append(i)

UCI = UCI.drop(index_to_drop)  # drop the rows

print(UCI)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[532621 rows x 8 columns]

In [72]:
UCI.isna().sum() #Number of Nan values in the Dataset

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     134697
Country             0
dtype: int64

In [73]:
UCI.loc[UCI['Description'].isna()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,12/7/2011 18:26,0.0,NaN,United Kingdom
535326,581203,23406,NaN,15,12/7/2011 18:31,0.0,NaN,United Kingdom
535332,581209,21620,NaN,6,12/7/2011 18:35,0.0,NaN,United Kingdom
536981,581234,72817,NaN,27,12/8/2011 10:33,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,12/8/2011 14:06,0.0,NaN,United Kingdom

In [74]:
UCI.loc[UCI['CustomerID'].isna()] #All the values from customer are empty

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,12/9/2011 10:26,4.13,NaN,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,12/9/2011 10:26,4.13,NaN,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,12/9/2011 10:26,4.96,NaN,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,12/9/2011 10:26,10.79,NaN,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,12/9/2011 10:26,1714.17,NaN,United Kingdom

In [96]:
np.array(UCI['Description'][0]+ UCI['Description'][1])

array('WHITE HANGING HEART T-LIGHT HOLDERWHITE METAL LANTERN',
      dtype='<U53')

In [76]:
UCI['Description']=UCI['Description'].fillna('Without register')

In [77]:
UCI['CustomerID']=UCI['CustomerID'].fillna('Without register')

In [139]:
keys=UCI['InvoiceNo']

In [140]:
tupla=tuple(keys)

In [141]:
values=UCI['StockCode'].values

In [142]:
dict={tupla:values}

In [146]:
invoice_order_dict = {}

for index, row in UCI.iterrows():
    invoice_no = row['InvoiceNo']
    order = row['Order']

    if invoice_no in invoice_order_dict:
        invoice_order_dict[invoice_no].append(order)
    else:
        invoice_order_dict[invoice_no] = [order]

# Imprimir el diccionario resultante
print(invoice_order_dict)

KeyError: 'Order'

In [145]:
list(dict.keys())

[('536365',
  '536365',
  '536365',
  '536365',
  '536365',
  '536365',
  '536365',
  '536366',
  '536366',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536367',
  '536368',
  '536368',
  '536368',
  '536368',
  '536369',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536370',
  '536371',
  '536372',
  '536372',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536373',
  '536374',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536375',
  '536376',
  '536376',
  '536377',
  '536377',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536378',
  '536380',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536381',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536382',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536384',
  '536385',
  '536385',
  '536385',
  '536385',
  '536385',
  '536385',
  '536385',
  '536386',
  '536386',
  '536386',
  '536387',
  '536387',
  '536387',
  '536387',
  '536387',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536388',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536389',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536390',
  '536392',
  '536392',
  '536392',
  '536392',
  '536392',
  '536392',
  '536392',
  '536392',
  '536392',
  '536392',
  '536393',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536394',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536395',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536396',
  '536397',
  '536397',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536398',
  '536399',
  '536399',
  '536400',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536401',
  '536402',
  '536402',
  '536402',
  '536403',
  '536403',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536404',
  '536405',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536406',
  '536407',
  '536407',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536408',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536409',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536412',
  '536414',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536415',
  '536416',
  '536416',
  '536416',
  '536416',
  '536416',
  '536416',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536420',
  '536423',
  '536423',
  '536423',
  '536423',
  '536423',
  '536423',
  '536423',
  '536423',
  '536423',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536425',
  '536437',
  '536437',
  '536437',
  '536437',
  '536437',
  '536437',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536446',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536460',
  '536463',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536464',
  '536466',
  '536466',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536477',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536488',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536500',
  '536502',
  '536502',
  '536502',
  '536502',
  '536502',
  '536508',
  '536508',
  '536514',
  '536514',
  '536514',
  '536514',
  '536514',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  '536520',
  ...)]